# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://blog.binaergewitter.de
title: Binärgewitter
subtitle: Web, Technologie und OpenSource Software 
author: Binärgewitter Crew
logo: /images/binaergewitter_logo.png
simple_search: http://google.com/search
keywords: podcast, technology, gadgets, web, opensource
description: Ein Podcast, der sich mit dem Web, Technologie und Open Source Software auseinander setzt


# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "%d.%m.%Y"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: http://feeds.feedburner.com/binaergewitter-podcast
subscribe_email:
# RSS feeds can list your email address if you like
email: info@binaergewitter.de

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to tilecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/recent_posts.html, asides/flattr.html, asides/github.html, asides/twitter.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# Podcast specific settings
podcast_category: Technology
podcast_copyright: Creative Commons BY-NC-SA 3.0 DE

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: binaergewitter
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: binaergewitter
twitter_tweet_count: 5
twitter_show_replies: false
twitter_follow_button: true
twitter_show_follower_count: false
twitter_tweet_button: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# Disqus Comments
disqus_short_name: binaergewitterpodcast
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id:

# Facebook Like
facebook_like: false

# Piwik Analytics
piwik_analytics_host: piwik.roothausen.de
piwik_analytics_id: 3

#Flattr
flattr_uid:	binaergewitter
flattr_category: audio
flattr_tags: podcast, tech, software
